import { NextResponse } from 'next/server';
import { z } from 'zod';
import pipeline from '@/orchestrator/PipelineFacade';

/**
 * PATCH /api/schedule/recalculate
 *
 * Handles schedule interruptions (Snooze, Missed Task).
 * Skips the AI — only the JS deterministic math runs, making this very fast.
 *
 * Request Body:
 * {
 *   workspace_id: string,
 *   interrupted_task_id: string,
 *   action: 'snooze' | 'missed',
 *   delay_minutes: number,
 *   busy_blocks: [{ busy: [{ start, end }] }],
 *   triggered_by: string
 * }
 */

const RecalculateRequestSchema = z.object({
  workspace_id: z.string().min(1),
  interrupted_task_id: z.string().min(1),
  action: z.enum(['snooze', 'missed', 'complete']),
  delay_minutes: z.number().min(0).optional(),
  busy_blocks: z.array(z.object({
    busy: z.array(z.object({
      start: z.string(),
      end: z.string(),
    })),
  })),
  triggered_by: z.string().min(1),
});

export async function PATCH(request) {
  let body;

  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { success: false, data: null, error: { code: 'INVALID_JSON', message: 'Request body is not valid JSON.' } },
      { status: 400 }
    );
  }

  const parseResult = RecalculateRequestSchema.safeParse(body);
  if (!parseResult.success) {
    return NextResponse.json(
      {
        success: false,
        data: null,
        error: { code: 'VALIDATION_FAILED', message: parseResult.error.issues[0].message },
      },
      { status: 400 }
    );
  }

  const { workspace_id, interrupted_task_id, action, delay_minutes, busy_blocks, triggered_by } = parseResult.data;

  const result = await pipeline.recalculateSchedule(
    workspace_id,
    interrupted_task_id,
    action,
    delay_minutes ?? 0,
    busy_blocks,
    triggered_by
  );

  if (result.success && result.data && result.data.scheduled) {
    result.data.scheduled = mapScheduledToCalendarEvents(result.data.scheduled);
  }

  const statusCode = result.success ? 200 : (result.error?.code === 'TASK_NOT_FOUND' ? 404 : 500);
  return NextResponse.json(result, { status: statusCode });
}

// ── Helper to convert scheduled DB tasks into FullCalendar events ──
const LOAD_COLORS = {
  High:   { bg: '#10b981', border: '#059669' },
  Medium: { bg: '#3b82f6', border: '#2563eb' },
  Low:    { bg: '#f59e0b', border: '#d97706' },
};

function colorForLoad(cognitiveLoad) {
  return LOAD_COLORS[cognitiveLoad] || LOAD_COLORS.Medium;
}

function mapScheduledToCalendarEvents(scheduledTasks) {
  const events = [];

  for (const task of scheduledTasks) {
    const color = colorForLoad(task.metadata?.cognitive_load || 'Medium');
    const taskId = task._id ? task._id.toString() : `gen_${Date.now()}_${events.length}`;

    for (const block of (task.schedule_blocks || [])) {
      events.push({
        id: taskId,
        title: task.metadata?.task_name || 'Task',
        start: block.start_time,
        end: block.end_time,
        backgroundColor: color.bg,
        borderColor: color.border,
        extendedProps: {
          description: `<p>Generated by SyncForge AI pipeline.</p>`,
          cognitive_load: task.metadata?.cognitive_load,
          estimated_minutes: task.metadata?.estimated_minutes,
          preferred_window: task.metadata?.preferred_window,
          splittable: task.metadata?.splittable,
          assigned_to: task.assigned_to || 'Current User',
        },
      });
    }
  }

  return events;
}
