import { NextResponse } from 'next/server';
import { z } from 'zod';
import serviceManager from '@/orchestrator/ServiceManager';

/**
 * POST /api/schedule/generate
 *
 * Full two-phase scheduling pipeline:
 *   Phase 1 (The Brain) — Gemini AI extracts structured tasks from multimodal inputs.
 *   Phase 2 (The Hands) — NUserBinPacking slots those tasks into free calendar bins.
 *
 * The AI adapter is obtained via ServiceManager (DI), which wraps it in
 * FallbackAIDecorator for automatic fault tolerance. The scheduler is also
 * provided by ServiceManager for easy future swapping.
 *
 * Request Body (per Internal API spec §4.1):
 * {
 *   workspace_id:     string,
 *   inputs:           [{ type: "text"|"image_base64", content: string }],
 *   user_preferences: { deep_work_hours: string[], max_daily_load_minutes: number }
 * }
 */

// ── Zod Request Validation ──────────────────────────────────────────────────

const GenerateRequestSchema = z.object({
  workspace_id: z.string().min(1, 'workspace_id is required.'),
  inputs: z.array(
    z.object({
      type: z.enum(['text', 'image_base64']),
      content: z.string(),
    })
  ).min(1, 'At least one input is required.'),
  existing_events: z.array(
    z.object({
      start: z.string(),
      end: z.string(),
    }).passthrough()
  ).optional().default([]),
  user_preferences: z.object({
    deep_work_hours: z.array(z.string()).optional().default(['09:00', '17:00']),
    max_daily_load_minutes: z.number().optional().default(240),
  }).optional().default({}),
});

// ── Color palette keyed by cognitive load ────────────────────────────────────
const LOAD_COLORS = {
  High:   { bg: '#10b981', border: '#059669' }, // emerald
  Medium: { bg: '#3b82f6', border: '#2563eb' }, // blue
  Low:    { bg: '#f59e0b', border: '#d97706' }, // amber
};

/**
 * Returns a color pair for a given cognitive_load label.
 */
function colorForLoad(cognitiveLoad) {
  return LOAD_COLORS[cognitiveLoad] || LOAD_COLORS.Medium;
}

/**
 * Converts the Phase 2 scheduled task array into FullCalendar event objects.
 *
 * Each scheduled task contains one or more schedule_blocks (splittable tasks
 * may span multiple time slots). Every block becomes its own calendar event
 * so FullCalendar renders them individually.
 *
 * @param {Array<Object>} scheduledTasks - Tasks with .metadata and .schedule_blocks[].
 * @returns {Array<Object>} FullCalendar-compatible event array.
 */
function mapScheduledToCalendarEvents(scheduledTasks) {
  const events = [];

  for (const task of scheduledTasks) {
    const color = colorForLoad(task.metadata.cognitive_load);

    for (const block of task.schedule_blocks) {
      events.push({
        id: `gen_${Date.now()}_${events.length}`,
        title: task.metadata.task_name,
        start: block.start_time,
        end: block.end_time,
        backgroundColor: color.bg,
        borderColor: color.border,
        extendedProps: {
          description: `<p>Generated by SyncForge AI pipeline.</p>`,
          cognitive_load: task.metadata.cognitive_load,
          estimated_minutes: task.metadata.estimated_minutes,
          preferred_window: task.metadata.preferred_window,
          splittable: task.metadata.splittable,
          assigned_to: task.assigned_to || 'Current User',
        },
      });
    }
  }

  return events;
}

// ── Route Handler ────────────────────────────────────────────────────────────

export async function POST(request) {
  const startTime = Date.now();
  let body;

  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { success: false, data: null, error: { code: 'INVALID_JSON', message: 'Request body is not valid JSON.' } },
      { status: 400 }
    );
  }

  // ── Zod Validation ──────────────────────────────────────────────────────
  const parseResult = GenerateRequestSchema.safeParse(body);
  if (!parseResult.success) {
    return NextResponse.json(
      {
        success: false,
        data: null,
        error: {
          code: 'VALIDATION_FAILED',
          message: parseResult.error.issues[0].message,
        },
      },
      { status: 400 }
    );
  }

  try {
    const { workspace_id, inputs, existing_events, user_preferences } = parseResult.data;

    // ── Parse multimodal inputs into the shapes the AI adapter expects ──

    const textPrompt = inputs
      .filter((i) => i.type === 'text')
      .map((i) => i.content)
      .join('\n');

    const base64Images = inputs
      .filter((i) => i.type === 'image_base64')
      .map((i) => ({
        inlineData: {
          mimeType: i.content.split(';')[0].replace('data:', '') || 'image/png',
          data: i.content.split(',')[1],
        },
      }));

    // ── Phase 1: The Brain (Gemini AI) ──────────────────────────────────
    // ServiceManager provides FallbackAIDecorator(geminiAdapter).
    // If the Gemini API is unavailable, the decorator catches and returns [].

    const aiService = await serviceManager.getAIService();
    const aiTasks = await aiService.generateStandard(
      workspace_id,
      'user_mvp',        // MVP: hardcoded user ID until auth is wired
      user_preferences,
      textPrompt,
      base64Images
    );

    // If the AI returned no tasks (empty input or fallback), return early.
    if (!aiTasks || aiTasks.length === 0) {
      return NextResponse.json(
        {
          success: true,
          data: [],
          error: null,
          meta: {
            timestamp: new Date().toISOString(),
            processing_ms: Date.now() - startTime,
            ai_tasks: [],
          },
        },
        { status: 200 }
      );
    }

    // ── Phase 2: The Hands (NUserBinPacking Scheduler) ──────────────────
    // Maps the deep_work_hours frontend field to the scheduler's work window.
    // Integrate existing events on the calendar as busy blocks so AI tasks schedule around them.
    const busyBlocks = existing_events.map(ev => ({
      start: ev.start,
      end: ev.end,
    }));

    const scheduler = serviceManager.getScheduler();
    const { scheduled, unscheduled, full } = scheduler.schedule(
      aiTasks,
      [{ busy: busyBlocks }],   // Pass existing tasks to find open gaps
      {
        work_day_start:       user_preferences?.deep_work_hours?.[0] || '09:00',
        work_day_end:         user_preferences?.deep_work_hours?.[1] || '17:00',
        deep_work_max_minutes: user_preferences?.max_daily_load_minutes || 240,
        buffer_minutes:       15,
      }
    );

    // ── Map to FullCalendar events ──────────────────────────────────────

    const calendarEvents = mapScheduledToCalendarEvents(scheduled);

    const processingMs = Date.now() - startTime;
    return NextResponse.json(
      {
        success: true,
        data: calendarEvents,
        error: null,
        meta: {
          timestamp: new Date().toISOString(),
          processing_ms: processingMs,
          ai_tasks: aiTasks,  // Phase 1 raw output for TaskBreakdown display
        },
      },
      { status: 200 }
    );
  } catch (err) {
    return NextResponse.json(
      {
        success: false,
        data: null,
        error: { code: 'GENERATION_FAILED', message: err.message },
        meta: { timestamp: new Date().toISOString(), processing_ms: Date.now() - startTime },
      },
      { status: 500 }
    );
  }
}
